### ISSUE TITLE
display playlists for users to select from during config

### ISSUE THREAD

**Issue by amcquade** [amcquade/fresh_script#30]

**Comment by gener1k** [comment]
Hi, I would like to work on this. To clarify, you would like to display the names of all the user's playlists during this step:  

![image](https://user-images.githubusercontent.com/18262405/47201803-f1e46180-d32f-11e8-8d00-a7542d1f5679.png)
Would you like them to then enter the playlist(s) by name rather than ID?

**Comment by adamfitzgibbon** [comment]
I was taking a look at this issue the other night but feel free to work on it! You'll probably want to modify the `addPlaylists` helper function by passing in the user token in to make a spotipy instance using `current_user_playlists()` I was going to just do the selection process the same way I wrote the  `removePlaylists` where you number the options and prompt them for the number they want to add.

**Comment by gener1k** [comment]
@adamfitzgibbon no worries! I haven't start this yet, so have at it 👍
